openapi: 3.0.3
info:
  title: Book Shelf - social experiment
  description: >
    This is an API for a book shelf. You can add whatever books you like.
    There is only one rule: do not add books that are not real.
    It is a social experiment to see if people will voluntarily obey the rules
    to create a better community.
  version: 2.0.0
servers:
  - url: https://boiling-dusk-49835-df388a71925c.herokuapp.com/api_v3/
  - url: http://127.0.0.1:8000/
tags:
  - name: books
    description: 'Books interactions'
  - name: authors
    description: 'Interactions with authors'
  - name: orders
    description: 'User orders'
  - name: users
    description: 'User interaction'
paths:
  /books/:
    get:
      tags:
        - books
      summary: Retrieve all books
      description: Returns books list
      operationId: getBooks
      parameters:
        - name: title
          in: query
          description: books name
          required: false
          schema:
            type: string
        - name: genre
          in: query
          description: books genre
          required: false
          schema:
            type: string
        - name: author
          in: query
          description: books author
          required: false
          schema:
            type: string
        - name: publish_year
          in: query
          description: publish year of the books
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book_does_not_found'
  /books/create/:
    post:
      security:
        - bearerAuth: []
      tags:
        - books
      summary: Add a new book and author to the store
      description: Add a new book to the store
      operationId: addBook
      requestBody:
        description: Create a new book in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book_post_request_body'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book_created'
        '400':
          description: Book already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book_exists'
  /books/{bookId}:
    get:
      tags:
        - books
      summary: Find book by ID
      description: Returns a single book
      operationId: getBookById
      parameters:
        - name: bookId
          in: path
          description: ID of book to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Not Found
  /books/update/{bookId}/:
    put:
      security:
        - bearerAuth: []
      tags:
        - books
      summary: Update book by ID
      description: Update book in the store
      operationId: updateBook
      parameters:
        - name: bookId
          in: path
          description: ID of book to put
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update book in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book_put_request_body'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book_after_update'
        '404':
          description: Not found
  /books/delete/{bookId}/:
    delete:
      security:
        - bearerAuth: []
      tags:
        - books
      summary: Delete book by ID
      description: Delete book from the store
      operationId: deleteBook
      parameters:
        - name: bookId
          in: path
          description: ID of book to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book_after_delete'
        '400':
          description: Does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book_does_not_exist_delete'
  /authors/:
    get:
      tags:
        - authors
      summary: Show all authors in the store with optional filters
      description: Returns authors list
      operationId: getAuthors
      parameters:
        - name: name
          in: query
          description: name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        '404':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author_does_not_exist'
  /authors/{authorId}:
    get:
      tags:
        - authors
      summary: Find author by ID
      description: Returns a single author
      parameters:
        - name: authorId
          in: path
          description: ID of author to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author_does_not_exist'
  /authors/create/:
    post:
      security:
        - bearerAuth: []
      tags:
        - authors
      summary: Add new author
      description: Add new author to the library
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorInput'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
  /authors/update/{id}/:
    put:
      security:
        - bearerAuth: []
      tags:
        - authors
      summary: Update the author
      description: Update the existent author by id
      parameters:
        - name: id
          in: path
          description: Author id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorInput'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: Not found
  /authors/delete/{id}:
    delete:
      security:
        - bearerAuth: []
      tags:
        - authors
      summary: Author delete
      description: Delete the existent author using id
      parameters:
        - name: id
          in: path
          description: Author id
          required: true
          schema:
              type: integer
      responses:
        '204':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author_does_not_exist'
  /order/:
    post:
      tags:
        - orders
      summary: Order the new book
      description: ordering the book
      requestBody:
        required: true
        content:  
          application/json:
            schema:
              $ref:  '#/components/schemas/Order_creation'
      responses:
        '201':
          description: Success
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/MonoAnswer'
        '400':
          description: Failed
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/OrderCreationFailed'         
  /users/register/:
    post:
      tags:
        - users
      summary: User registration
      description: New user registration form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User_creation_error'
  /users/login/:
    post:
      tags:
        - users
      summary: User login
      description: User login form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User_login_successful'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User_login_error_form'
        '401':
          description: Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User_login_error'

components:
  schemas:
    Book:
      type: object
      properties:
        model:
          type: string
          example: book_shelf.book
        pk:
          type: integer
          format: int64
          example: 3
        fields:
          type: object
          properties:
            title:
              type: string
              example: The Lord of the Rings
            publish_year:
              type: integer
              description: The year the book was published
              example: 1954
            author:
              type: integer
              description: The author of the book
              example: 1
            genre:
              type: string
              description: The genre of the book
              example: Fantasy
    Book_created:
      type: object
      properties:
        title:
          type: string
          example: The Lord of the Rings
        publish_year:
          type: integer
          example: 1954
        author:
          type: integer
          example: 1
        genre:
          type: string
          example: Fantasy
    Book_post_request_body:
      type: object
      properties:
        title:
          type: string
          example: The Adventures of Sherlock Holmes
        author:
          type: integer
          example: 1
        genre:
          type: string
          example: Novel
        publish_year:
          type: string
          example: 1892
    Book_exists:
      type: object
      properties:
        message:
          type: string
          example: Book already exists
        status:
          type: integer
          example: 400
    Book_does_not_found:
      type: object
      properties:
        message:
          type: string
          example: No books found
        status:
          type: integer
          example: 404
    Book_put_request_body:
      type: object
      properties:
        title:
          type: string
          example: Update name
        author:
          type: string
          example: Arthur Conan Doyle
        genre:
          type: string
          example: Update genre
        publish_year:
          type: string
          example: 1892
    Book_after_update:
      type: object
      properties:
        id:
          type: integer
          example: 4
        title:
          type: string
          example: Update name
        publish_year:
          type: integer
          example: 1892
        author:
          type: integer
          example: 1
        genre:
          type: string
          example: Update genre
    Book_after_delete:
      type: object
    Book_does_not_exist_delete:
      type: object
      properties:
        Error:
          type: string
          example: Book does not exist
        status:
          type: integer
          example: 400
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: John 2... Still trying...
    AuthorInput:
      type: object
      properties:
        name:
          type: string
          example: Artur Conan Doyle
    Author_does_not_exist:
      type: object
      properties:
        Error:
          type: string
          example: Author does not exist
        status:
          type: integer
          example: 404
    UserRegistration:
      type: object
      properties:
        username:
          type: string
          example: test_username
        email:
          type: string
          example: example@gmail.com
        password:
          type: string
          example: Example244685071204
    User:
      type: object
      properties:
        username:
          type: string
          example: test3
        email:
          type: string
          example: test3@test.com

    User_creation_error:
      type: object
      properties:
        username:
          type: string
          example: A user with that username already exists.
        email:
          type: string
          example: Email already exists
        password:
          type: array
          items:
            type: string
            example: ['This password is too short. It must contain at least 8 characters.', 'This password is too common.', 'This password is entirely numeric.']
    UserLogin:
      type: object
      properties:
        username:
          type: string
          example: test_username
        password:
          type: string
          example: Example244685071204
    User_login_successful:
      type: object
      properties:
        refresh:
          type: string
          example: your refresh token
        access:
         type: string
         example: your access token
        email:
          type: string
          example: example@gmail.com
    User_login_error:
      type: object
      properties:
       detail:
        type: string
        example: No active account found with the given credentials
    User_login_error_form:
      type: object
      properties:
        username:
          type: string
          example: [
        "This field may not be blank."
    ]
        password:
          type: string
          example: [
        "This field may not be blank."
        ]
    
    Order_creation:
      type: object
      properties:
        order:
          type: array
          items:
            type: object
            properties:
              book_id:
                type: integer
                example: 2
              quantity:
                type: integer
                example: 1
            required:
              - book_id
              - quantity
          example:
            - book_id: 2
              quantity: 1
            - book_id: 3
              quantity: 12
    OrderCreationFailed:
      type: object
      properties:
        detail:
          type: string
          example: "JSON parse error - Expecting property name enclosed in double quotes: line ... column ... (char ...)"
    MonoAnswer:
      type: object
      properties:
        url:
          type: string
          example: https://pay.mbnk.biz/654321123456rRk4H2hXxoJiv
        id:
          type: integer
          example: 17
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT