# Generated by Django 4.2.3 on 2023-08-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiv3", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
