# Generated by Django 4.2.3 on 2023-08-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiv3", "0002_book_publish_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
