# Generated by Django 4.2.3 on 2023-08-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiv3", "0003_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urls", models.CharField(max_length=1000)),
            ],
        ),
    ]
