name: codecov

on: [push, pull_request]

jobs:
  your-job-name:
    name: EVALUATE THE COVERAGE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Replace 'x' with your desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt # Replace with the command to install your project dependencies

      - name: Run pytest
        run: |
          pytest --cov app

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
