name: Code Coverage Report

on:
  push:
    branches:
      - main

jobs:
  code-coverage:
    name: Run Tests with Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace 'x' with your desired Python version
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt # Replace with the command to install your project dependencies
          pip install pytest pytest-cov codecov # Install pytest, pytest-cov, and codecov
        
      - name: Run pytest with coverage
        run: pytest --cov app # Replace 'app' with the appropriate package name containing your code
        
      - name: Upload coverage data to Codecov
        run: codecov
