name: Codecov workflow
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.11'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pip install requests   # Add this line for 'requests'
        pip install responses  # Add this line for 'responses'
        pip install django
    - name: Run Tests
      run: |
        DJANGO_SETTINGS_MODULE=homework_20_21.settings pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: 4edc96c3-6c0a-46b4-bd2d-412b9a7d9a58
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        verbose: true
        
