name: CODECOV

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    name: EVALUATE THE COVERAGE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
