name: CODECOV

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    name: EVALUATE THE COVERAGE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4' # Replace 'x' with your desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt # Replace with the command to install your project dependencies

      - name: Run pytest
        run: |
          pytest 

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
