name: pytest

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies and run tests
        run: |
          pip install -r requirements.txt
          pytest
